eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

server:
  port: 14641

spring:
  application:
    name: comment-service

  data:
    mongodb:
      uri: ${DB_URI:mongodb://localhost:27017/high-five}
      database: high-five
      uuid-representation: standard
